### ISSUE TITLE
Attempt to index

### ISSUE THREAD

**Issue by nalmeth** [laytya/EQL3#5]
Error spam when accepting a quest:

ERROR: Interface\AddOns\EQL3\EQL3_Tracker.lua:360: attempt to index local 'watchText' (a nil value)

**Comment by galenbrazell** [comment]
Getting the same error as well.

![image](https://user-images.githubusercontent.com/3221476/43625519-48ffed56-96a2-11e8-9640-38e69f9c7e69.png)

Happened when I accepted Jin'Zil's Forest Magic for this one, but happens on other accepted quests too.

Seems to occur due to being auto-added to tracker (Questie). Removing it from tracker stops the spam.
